###############################################################
# Program:
#     Assignment 04, Ecommerce Product Inventory
#     Brother Macbeth, CS165
# Author:
#     Lance Bunch
# Summary:
#     This code takes in four bits of information and displays it based off
#       of the users decision. It does basic math Calculation to give a good
#		visual of the information that was input.
#
#	Estimated Completion Time: 3.0 hrs
#	Actual Completion Time: 2.75 hrs
#
#	What was one of the most difficult parts for me was actually just
#	the math about how to add the 10 cents for each pound over 5.
#	The formatting was also a little frustrating but everything
# 	got figured out in the long run. The bes thing that I learned is
#	that classes help move information a lot easier than procedural
#	Programming.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

