###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Macbeth, CS165
# Author:
#     Lance Bunch
# Summary:
#     This code implements constructors, accessors, and mutators 
#	  to showcase their function and usability between classes.
#	  Following the procedures I can see how giving this code
#	  to a differe programmer or "client" and the book puts it
#  	  helps them to better implement other functions and classes.
#
#	Estimate: 4.0 Hrs
#	Actual:   3.5 Hrs
# Problems:
#	  The biggest problem I encountered was because of bugs from last
#	  week's product.h and .cpp file. I had one function as a void
#	  that should have been a double. The other functions it called 
#	  displayed things that should've been displayed in a different
#	  area to increase reusability of the function. Because of this
#	  there were some errors with compiling and cout's.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

