###############################################################
# Program:
#     Team Activity 04, Classes
#     Brother Macbeth, CS165
# Author:
#     Lance Bunch
# Summary:
#     Put your summary code here... 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : rational.h rational.cpp ta04.cpp
	g++ rational.cpp ta04.cpp

